name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install shellcheck
      run: sudo apt-get update && sudo apt-get install -y shellcheck

    - name: Run shellcheck
      run: shellcheck ghq-utils.sh

    - name: Install BATS
      run: |
        sudo apt-get install -y bats

    - name: Run BATS tests
      run: bats test_ghq_utils.bats
